var catalog = [
    {
        _id: "1s1001",
        price: 8.00,
        stock: 10,
        title: "Cinnamon",
        image: "img-Cinnamon.jpeg",
        discount: 0,
        category: "Spices",
      },
      {
        _id: "1s1002",
        price: 10.00,
        stock: 20,
        title: "Nutmeg",
        image: "img-Nutmeg.png",
        discount: 0,
        category: "Spices",
      },
      {
        _id: "1s1003",
        price: 16.0,
        stock: 20,
        title: "Clove",
        image: "imm-Cloves.jpeg",
        discount: 0,
        category: "Spices",
      },
      {
        _id: "1s1004",
        price: 10.0,
        stock: 20,
        title: "Tumeric",
        image: "img-Tumeric.jpeg",
        discount: 0,
        category: "Spices",
      },
      {
        _id: "1s1005",
        price: 16.0,
        stock: 20,
        title: "Bay Leaf",
        image: "img-Bay Leaf.webp",
        discount: 0,
        category: "Spices",
      },
      {
        _id: "1s1006",
        price: 14.0,
        stock: 20,
        title: "Ginger",
        image: "img-Ginger.jpeg",
        discount: 0,
        category: "Spices",
      },
      {
        _id: "1s1007",
        price: 32.0,
        stock: 20,
        title: "Allspice",
        image: "img-Allspice.jpeg",
        discount: 0,
        category: "Spices",
      }
    ]